// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// aes_io
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of inptext_V
//        bit 31~0 - inptext_V[31:0] (Read/Write)
// 0x18 : Data signal of inptext_V
//        bit 31~0 - inptext_V[63:32] (Read/Write)
// 0x1c : Data signal of inptext_V
//        bit 31~0 - inptext_V[95:64] (Read/Write)
// 0x20 : Data signal of inptext_V
//        bit 31~0 - inptext_V[127:96] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of key_V
//        bit 31~0 - key_V[31:0] (Read/Write)
// 0x2c : Data signal of key_V
//        bit 31~0 - key_V[63:32] (Read/Write)
// 0x30 : Data signal of key_V
//        bit 31~0 - key_V[95:64] (Read/Write)
// 0x34 : Data signal of key_V
//        bit 31~0 - key_V[127:96] (Read/Write)
// 0x38 : Control signal of outtext_V
//        bit 0  - outtext_V_ap_vld (Read/COR)
//        others - reserved
// 0x3c : Data signal of outtext_V
//        bit 31~0 - outtext_V[31:0] (Read)
// 0x40 : Data signal of outtext_V
//        bit 31~0 - outtext_V[63:32] (Read)
// 0x44 : Data signal of outtext_V
//        bit 31~0 - outtext_V[95:64] (Read)
// 0x48 : Data signal of outtext_V
//        bit 31~0 - outtext_V[127:96] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAESTEST_AES_IO_ADDR_AP_CTRL        0x00
#define XAESTEST_AES_IO_ADDR_GIE            0x04
#define XAESTEST_AES_IO_ADDR_IER            0x08
#define XAESTEST_AES_IO_ADDR_ISR            0x0c
#define XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA 0x14
#define XAESTEST_AES_IO_BITS_INPTEXT_V_DATA 128
#define XAESTEST_AES_IO_ADDR_KEY_V_DATA     0x28
#define XAESTEST_AES_IO_BITS_KEY_V_DATA     128
#define XAESTEST_AES_IO_ADDR_OUTTEXT_V_CTRL 0x38
#define XAESTEST_AES_IO_ADDR_OUTTEXT_V_DATA 0x3c
#define XAESTEST_AES_IO_BITS_OUTTEXT_V_DATA 128

