// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaestest.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAestest_CfgInitialize(XAestest *InstancePtr, XAestest_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Aes_io_BaseAddress = ConfigPtr->Aes_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAestest_Start(XAestest *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL) & 0x80;
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAestest_IsDone(XAestest *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAestest_IsIdle(XAestest *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAestest_IsReady(XAestest *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAestest_EnableAutoRestart(XAestest *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL, 0x80);
}

void XAestest_DisableAutoRestart(XAestest *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_AP_CTRL, 0);
}

void XAestest_SetInptext_v(XAestest *InstancePtr, XAestest_Inptext_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 0, Data.word_0);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 4, Data.word_1);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 8, Data.word_2);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 12, Data.word_3);
}

XAestest_Inptext_v XAestest_GetInptext_v(XAestest *InstancePtr) {
    XAestest_Inptext_v Data;

    Data.word_0 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 0);
    Data.word_1 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 4);
    Data.word_2 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 8);
    Data.word_3 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_INPTEXT_V_DATA + 12);
    return Data;
}

void XAestest_SetKey_v(XAestest *InstancePtr, XAestest_Key_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 0, Data.word_0);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 4, Data.word_1);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 8, Data.word_2);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 12, Data.word_3);
}

XAestest_Key_v XAestest_GetKey_v(XAestest *InstancePtr) {
    XAestest_Key_v Data;

    Data.word_0 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 0);
    Data.word_1 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 4);
    Data.word_2 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 8);
    Data.word_3 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_KEY_V_DATA + 12);
    return Data;
}

XAestest_Outtext_v XAestest_GetOuttext_v(XAestest *InstancePtr) {
    XAestest_Outtext_v Data;

    Data.word_0 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_OUTTEXT_V_DATA + 0);
    Data.word_1 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_OUTTEXT_V_DATA + 4);
    Data.word_2 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_OUTTEXT_V_DATA + 8);
    Data.word_3 = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_OUTTEXT_V_DATA + 12);
    return Data;
}

u32 XAestest_GetOuttext_vVld(XAestest *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_OUTTEXT_V_CTRL);
    return Data & 0x1;
}

void XAestest_InterruptGlobalEnable(XAestest *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_GIE, 1);
}

void XAestest_InterruptGlobalDisable(XAestest *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_GIE, 0);
}

void XAestest_InterruptEnable(XAestest *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_IER);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_IER, Register | Mask);
}

void XAestest_InterruptDisable(XAestest *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_IER);
    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_IER, Register & (~Mask));
}

void XAestest_InterruptClear(XAestest *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAestest_WriteReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_ISR, Mask);
}

u32 XAestest_InterruptGetEnabled(XAestest *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_IER);
}

u32 XAestest_InterruptGetStatus(XAestest *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAestest_ReadReg(InstancePtr->Aes_io_BaseAddress, XAESTEST_AES_IO_ADDR_ISR);
}

